In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [3]:
df=pd.read_csv('https://raw.githubusercontent.com/Jcharis/Python-Machine-Learning/master/Gender%20Classification%20With%20%20Machine%20Learning/names_dataset.csv')

In [4]:
df.head()

index       name sex
0      0       Mary   F
1      1       Anna   F
2      2       Emma   F
3      3  Elizabeth   F
4      4     Minnie   F

In [5]:
df.isnull().sum()

index    0
name     0
sex      0
dtype: int64

In [6]:
df.sex.replace(to_replace=['F','M'],value=[0,1],inplace=True)

In [7]:
df.sex.unique()

array([0, 1])

In [8]:
Xfeatures =df['name']

In [9]:
cv = TfidfVectorizer(min_df=1,stop_words='english',use_idf=True)

In [10]:
x = cv.fit_transform(Xfeatures)

In [ ]:
#cv.get_feature_names()

In [11]:
x
y = df.sex

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [13]:
clf = MultinomialNB()
clf.fit(x_train,y_train)
acctest=clf.score(x_test,y_test)
acctrain=clf.score(x_train,y_train)

In [14]:
# Accuracy of our Model
print("Accuracy of Test Model",acctest*100,"%")
print("Accuracy of Train Model",acctrain*100,"%")

Accuracy of Test Model 64.06622702399326 %
Accuracy of Train Model 99.97895274892133 %


In [15]:
print(cv.idf_)

[11.76875864 11.76875864 11.76875864 ... 11.76875864 11.76875864
 11.76875864]


Predict

In [16]:
# Sample1 Prediction
sample_name = ["Mary"]
vect = cv.transform(sample_name).toarray()

In [17]:
vect

array([[0., 0., 0., ..., 0., 0., 0.]])

In [18]:
# Female is 0, Male is 1
clf.predict(vect)

array([0])

In [19]:
print("Please enter a name to predict its gender : ")
name=[input()]
vect = cv.transform(name).toarray()

if clf.predict(vect)==0:
  print("Female")
else:
  print("Male")

Please enter a name to predict its gender : 
rahat
Female


In [20]:
def predictgender(name):
  vect = cv.transform(name).toarray()
  vect = cv.transform(name).toarray()
  if clf.predict(vect)==0:
    print("Female")
  else:
    print("Male")


In [21]:
# number of elements
n = int(input("Enter number of elements : "))
  
# Below line read inputs from user using map() function 
name1 = list(map(str,input("\nEnter the names : ").strip().split()))[:n]

for ele in enumerate(n):
  predictgender(name1)

Enter number of elements : 5

Enter the names : nasif,jj,kila,sain,jer


TypeError: ignored

In [ ]:
# number of elements
n = int(input("Enter number of elements : "))
  
# Below line read inputs from user using map() function 
name1 = list(map(str,input("\nEnter the names : ").strip().split()))[:n]

vect = cv.transform(name1).toarray()

for ele in enumerate(name1):
  if clf.predict(vect)==0:
    print("Female")
  else:
    print("Male")

Enter number of elements : 5

Enter the names : samin reshad mahi ifti sou


ValueError: ignored